#!/usr/bin/env python3
"""
Read blocks.txt (Stadium) + blocks_blue_bay.txt, blocks_green_coast.txt,
blocks_red_island.txt, blocks_white_shore.txt. Generate blocks_generated.as with
per-Vista arrays (SCENERY_<Vista>, BLOCKS_<Vista>_<Type>_<Role>) and GetBlockFromPoolImpl.
Run clean-vista-blocks.py first if Vista files have log format.
"""
from pathlib import Path
from collections import defaultdict

REPO = Path(__file__).resolve().parent
OUTPUT_AS = REPO / "blocks_generated.as"

VISTA_FILES = [
    (REPO / "blocks.txt", "Stadium"),
    (REPO / "blocks_blue_bay.txt", "BlueBay"),
    (REPO / "blocks_green_coast.txt", "GreenCoast"),
    (REPO / "blocks_red_island.txt", "RedIsland"),
    (REPO / "blocks_white_shore.txt", "WhiteShore"),
]

TRACK_TYPES = ("Tech", "Dirt", "Ice", "Water", "Plastic", "Grass", "Snow", "Rally", "Bump", "Other")
ROLES = (
    "Start", "Finish", "Straight", "Turn1", "Turn2", "Turn3", "Turn4", "Turn5",
    "Slope", "Slope2", "Checkpoint", "Turbo1", "Turbo2", "TurboR",
    "Booster1", "Booster2", "NoEngine", "SlowMotion", "Fragile", "NoSteer",
    "Reset", "Cruise", "NoBrake", "Cool1", "Cool2", "Connector", "End", "Other",
)

# CURR_BLOCKS value -> Type for pool lookup
BLOCKSTYLE_TO_TYPE = [
    ("TechBlocks", "Tech"), ("OpenTechRoadBlocks", "Tech"), ("PlatformTechBlocks", "Tech"),
    ("DirtBlocks", "Dirt"), ("OpenDirtRoadBlocks", "Dirt"), ("PlatformDirtBlocks", "Dirt"),
    ("IceBlocks", "Ice"), ("IceWallBlocks", "Ice"), ("OpenIceRoadBlocks", "Ice"), ("PlatformIceBlocks", "Ice"),
    ("WaterBlocks", "Water"),
    ("PlasticBlocks", "Plastic"),
    ("OpenGrassRoadBlocks", "Grass"), ("PlatformGrassBlocks", "Grass"),
    ("SausageBlocks", "Bump"),
    ("SnowBlocks", "Snow"),
    ("RallyBlocks", "Rally"),
]


def role_from_name(name: str) -> str:
    n = name
    if "Start" in n and "Slope2Start" not in n and "LoopStart" not in n:
        return "Start"
    if "Finish" in n:
        return "Finish"
    if "Checkpoint" in n:
        return "Checkpoint"
    if "Slope2" in n:
        return "Slope2"
    if "SlopeBase" in n or "Slope" in n:
        return "Slope"
    if "Curve5" in n:
        return "Turn5"
    if "Curve4" in n:
        return "Turn4"
    if "Curve3" in n:
        return "Turn3"
    if "Curve2" in n:
        return "Turn2"
    if "Curve1" in n:
        return "Turn1"
    if "TurboRoulette" in n:
        return "TurboR"
    if "SpecialTurbo2" in n:
        return "Turbo2"
    if "SpecialTurbo" in n:
        return "Turbo1"
    if "SpecialBoost2" in n:
        return "Booster2"
    if "SpecialBoost" in n:
        return "Booster1"
    if "NoEngine" in n:
        return "NoEngine"
    if "SlowMotion" in n:
        return "SlowMotion"
    if "Fragile" in n:
        return "Fragile"
    if "NoSteering" in n:
        return "NoSteer"
    if "Reset" in n and "Special" in n:
        return "Reset"
    if "Cruise" in n:
        return "Cruise"
    if "NoBrake" in n:
        return "NoBrake"
    if "TrackWallTo" in n:
        return "End"
    if "ToRoad" in n or "ToDecoWall" in n or "ToTrackWall" in n or "ToOpen" in n:
        return "Connector"
    if "Ramp" in n or "Narrow" in n or "Wave" in n:
        if "RampLow" in n or "RampMed" in n:
            return "Cool1"
        return "Cool2"
    if "Straight" in n or "Base" in n:
        return "Straight"
    return "Other"


def parse_file(path: Path) -> tuple[list[str], defaultdict]:
    scenery = []
    pools = defaultdict(list)
    if not path.exists():
        return scenery, pools
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("|", 2)
        if len(parts) < 3:
            continue
        id_name = parts[0].strip()
        kind = parts[1].strip()
        typ = parts[2].strip()
        if kind == "Scenery" or typ == "Scenery":
            scenery.append(id_name)
            continue
        role = role_from_name(id_name)
        t = typ if typ in TRACK_TYPES else "Other"
        pools[(t, role)].append(id_name)
    return scenery, pools


def main() -> None:
    # (vista -> scenery list), (vista, type, role) -> list of IdName
    all_scenery = {}
    all_pools = defaultdict(list)

    for path, vista in VISTA_FILES:
        scenery, pools = parse_file(path)
        all_scenery[vista] = sorted(set(scenery))
        for (t, role), names in pools.items():
            all_pools[(vista, t, role)] = sorted(set(names))

    out = []
    out.append("// Auto-generated by generate_blocks_as.py (multi-Vista). Do not edit by hand.")
    out.append("")

    # Per-Vista scenery
    for vista in ["Stadium", "BlueBay", "GreenCoast", "RedIsland", "WhiteShore"]:
        arr = all_scenery.get(vista, [])
        out.append(f"array<string> SCENERY_{vista} = {{")
        for name in arr:
            out.append(f'\t"{name}",')
        out.append("};")
        out.append("")

    # Backward compat: SCENERY_BLOCKS = Stadium
    out.append("array<string> SCENERY_BLOCKS = SCENERY_Stadium;")
    out.append("")

    # Per (Vista, Type, Role) arrays
    for vista in ["Stadium", "BlueBay", "GreenCoast", "RedIsland", "WhiteShore"]:
        for t in TRACK_TYPES:
            for role in ROLES:
                key = (vista, t, role)
                if key not in all_pools:
                    continue
                arr = all_pools[key]
                var = f"BLOCKS_{vista}_{t}_{role}"
                out.append(f"array<string> {var} = {{")
                for name in arr:
                    out.append(f'\t"{name}",')
                out.append("};")
                out.append("")

    # GetBlockFromPoolImpl(role): switch on blocks::CURR_VISTA, then blocks::CURR_BLOCKS, call blocks::PickFromPool
    rd_fallbacks = {
        "Straight": "RD_STRAIGHT", "Turn1": "RD_TURN1", "Turn2": "RD_TURN2",
        "Slope": "RD_UP1", "Slope2": "RD_UP2", "Checkpoint": "RD_CP",
        "Cool1": "RD_COOL1", "Cool2": "RD_COOL2",
        "Turbo1": "RD_TURBO1", "Turbo2": "RD_TURBO2", "TurboR": "RD_TURBOR",
        "Booster1": "RD_BOOSTER1", "Booster2": "RD_BOOSTER2",
        "NoEngine": "RD_NOENGINE", "SlowMotion": "RD_SLOWMOTION", "Fragile": "RD_FRAGILE",
        "NoSteer": "RD_NOSTEER", "Reset": "RD_RESET", "Cruise": "RD_CRUISE", "NoBrake": "RD_NOBRAKE",
    }

    out.append("// Vista-aware pool lookup; uses blocks::CURR_VISTA and blocks::CURR_BLOCKS.")
    out.append("string GetBlockFromPoolImpl(const string &in role)")
    out.append("{")

    for role in ROLES:
        fallback = rd_fallbacks.get(role, "RD_STRAIGHT")
        out.append(f'\tif (role == "{role}") {{')
        for vista in ["Stadium", "BlueBay", "GreenCoast", "RedIsland", "WhiteShore"]:
            out.append(f'\t\tif (blocks::CURR_VISTA == "{vista}") {{')
            for style, typ in BLOCKSTYLE_TO_TYPE:
                key = (vista, typ, role)
                if key not in all_pools:
                    continue
                var = f"BLOCKS_{vista}_{typ}_{role}"
                out.append(f'\t\t\tif (blocks::CURR_BLOCKS == "{style}") return blocks::PickFromPool({var}, blocks::{fallback});')
            out.append(f'\t\t\treturn blocks::{fallback};')
            out.append("\t\t}")
        out.append(f'\t\treturn blocks::{fallback};')
        out.append("\t}")
    out.append("\treturn blocks::RD_STRAIGHT;")
    out.append("}")

    OUTPUT_AS.write_text("\n".join(out), encoding="utf-8")
    total_track = sum(len(v) for k, v in all_pools.items())
    total_scenery = sum(len(v) for v in all_scenery.values())
    print(f"Wrote {total_scenery} scenery (per Vista), {total_track} track entries -> {OUTPUT_AS}", flush=True)


if __name__ == "__main__":
    main()
